/**
 * Tests that commitChanges stages the entire repository (not just the cwd
 * subdirectory) and refuses to report success when the working tree is still
 * dirty after the commit.
 */

import { describe, test, expect, beforeEach, afterEach } from "bun:test";
import { execSync } from "child_process";
import { chmodSync, existsSync, mkdirSync, rmSync, writeFileSync } from "fs";
import { join } from "path";
import { Utils } from "../src/lib/utils";

describe("Commit scope and post-commit cleanliness guards", () => {
  let testDir: string;
  let repoDir: string;
  let subDir: string;

  beforeEach(() => {
    testDir = join(
      require("os").tmpdir(),
      `commit-scope-test-${Date.now()}-${Math.random().toString(36).substring(7)}`,
    );
    repoDir = join(testDir, "test-repo");
    subDir = join(repoDir, "packages", "code");
    mkdirSync(subDir, { recursive: true });

    execSync("git init", { cwd: repoDir });
    execSync("git config user.email 'test@test.com'", { cwd: repoDir });
    execSync("git config user.name 'Test User'", { cwd: repoDir });

    writeFileSync(join(repoDir, "README.md"), "# Test Repo\n", "utf8");
    execSync("git add .", { cwd: repoDir });
    execSync("git commit -m 'Initial commit'", { cwd: repoDir });
    execSync("git checkout -b feature/test-123", { cwd: repoDir });
  });

  afterEach(() => {
    try {
      if (existsSync(testDir)) {
        rmSync(testDir, { recursive: true, force: true });
      }
    } catch (e) {
      // Ignore cleanup errors
    }
  });

  test("commits changes outside the cwd subdirectory", async () => {
    // Change inside the cwd subdirectory and changes elsewhere in the repo
    writeFileSync(join(subDir, "inside.txt"), "inside\n", "utf8");
    writeFileSync(join(repoDir, "outside.txt"), "outside\n", "utf8");
    writeFileSync(join(repoDir, "README.md"), "# Test Repo (updated)\n", "utf8");

    // Run the commit from the subdirectory, as when devintern is launched
    // from a monorepo package
    const result = await Utils.commitChanges("TEST-123", "Test commit", { cwd: subDir });

    expect(result.success).toBe(true);
    expect(await Utils.hasUncommittedChanges(repoDir)).toBe(false);

    const committed = execSync("git show --name-only --format= HEAD", { cwd: repoDir })
      .toString()
      .trim()
      .split("\n");
    expect(committed).toContain("packages/code/inside.txt");
    expect(committed).toContain("outside.txt");
    expect(committed).toContain("README.md");
  });

  test("sweeps files generated by hooks during the commit into the same commit", async () => {
    // Idempotent pre-commit hook: creates an untracked file once
    const hookPath = join(repoDir, ".git", "hooks", "pre-commit");
    writeFileSync(hookPath, "#!/bin/sh\n[ -f generated.txt ] || echo generated > generated.txt\n");
    chmodSync(hookPath, 0o755);

    writeFileSync(join(repoDir, "change.txt"), "change\n", "utf8");

    const result = await Utils.commitChanges("TEST-123", "Test commit", { cwd: repoDir });

    expect(result.success).toBe(true);
    expect(await Utils.hasUncommittedChanges(repoDir)).toBe(false);

    const committed = execSync("git show --name-only --format= HEAD", { cwd: repoDir })
      .toString()
      .trim()
      .split("\n");
    expect(committed).toContain("change.txt");
    expect(committed).toContain("generated.txt");
  });

  test("fails loudly when the tree cannot be made clean after the commit", async () => {
    // Pathological pre-commit hook: dirties the tree on every run, so even
    // the amend sweep leaves uncommitted changes behind
    const hookPath = join(repoDir, ".git", "hooks", "pre-commit");
    writeFileSync(hookPath, "#!/bin/sh\necho more >> generated.txt\n");
    chmodSync(hookPath, 0o755);

    writeFileSync(join(repoDir, "change.txt"), "change\n", "utf8");

    const result = await Utils.commitChanges("TEST-123", "Test commit", { cwd: repoDir });

    expect(result.success).toBe(false);
    expect(result.message).toContain("partial commit");
  });
});
